### ISSUE TITLE
Found cuDNN: v?  (include: /usr/local/cuda-11.0/include, library: /usr/local/cuda-11.0/lib64/libcudnn.so)

### ISSUE THREAD

**Issue by ZiyueWu59** [Karbo123/segmentator#11]
When I run 
```
cmake .. -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))") -DCMAKE_INSTALL_PREFIX=`python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'`
```
I met this problem.:

```
-- Caffe2: CUDA detected: 11.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-11.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.0
-- Caffe2: Header version is: 11.0
-- Found cuDNN: v?  (include: /usr/local/cuda-11.0/include, library: /usr/local/cuda-11.0/lib64/libcudnn.so)
CMake Error at /home/tjut_wuziyue/anaconda3/envs/uniseg3d/lib/python3.10/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:186 (message):
  PyTorch requires cuDNN 7 and above.
Call Stack (most recent call first):
  /home/anaconda3/envs/uniseg3d/lib/python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:92 (include)
  /home/anaconda3/envs/uniseg3d/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!

```

 Could you help me to solve it?

**Comment by Karbo123** [comment]
I am not absolutely sure, the error said "PyTorch requires cuDNN 7 and above." You may try another pytorch version, maybe using `torch<2` will solve the problem. Or you may try to install cuDNN?

**Comment by ZiyueWu59** [comment]
> I am not absolutely sure, the error said "PyTorch requires cuDNN 7 and above." You may try another pytorch version, maybe using `torch<2` will solve the problem. Or you may try to install cuDNN?

Hi, I use torch with version `1.12.1`, and I actually install cuDNN. My version infos:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

```
```
Python 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:24:24) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.12.1+cu113'
>>> torch.version.cuda
'11.3'
>>> torch.backends.cudnn.version()
8400
>>> torch.cuda.is_available()
True
>>> exit()

```

**Comment by Karbo123** [comment]
You may try:
- I tested with Colab, and even colab can configurate successfully, as given in [the link](https://colab.research.google.com/drive/15fgfbHcyRg6n-vO-3C19tEArgj41fN8z?usp=sharing). I think you may pass additionally `-DCAFFE2_USE_CUDNN=0` to cmake. Pay attention to the log info, there are lots of useful tips

![image](https://github.com/user-attachments/assets/ef293882-dc86-4efc-884a-4e7225ad811b)

![image](https://github.com/user-attachments/assets/ac62aa7b-bc49-4000-b02b-0b9cab9ee9b7)

And this file (`/usr/local/lib/python3.10/dist-packages/torch/share/cmake/Caffe2/public/cuda.cmake`) is helpful

If this cannot work, try considering the followings
- You may try `PyTorch 1.8` or older because it is developed with such an old version
- You may install pytorch with `conda`
- Other people wrote a new way to install it, see [here](https://github.com/Karbo123/segmentator/pull/6), it might be helpful to you
- Actually it does not depend on cuDNN in our code
